### ISSUE TITLE
Data-URI

### ISSUE THREAD

**Issue by iansoper** [atlemo/SubtlePatterns#1]
Have you considered having copy and paste data-uris generated for each pattern? That would make it very easy for a designer to copy and paste into a stylesheet.

**Comment by atlemo** [comment]
Hi
To be honest I'm not sure how I'd go about doing it?

**Comment by DanielRuf** [comment]
You could use this generator: http://www.greywyvern.com/code/php/binary2base64
Just paste the direct url to the existing image(s) and generate the corresponding base64 / data uri code for each image

**Comment by atlemo** [comment]
Ah, that would be too much of a manual job. If anyone want's to use the patterns as Base64 they can use the generator on the specific pattern they need. 
I'll include a link to the one you recommended in the readme.
Cheers.

**Comment by DanielRuf** [comment]
Currently working on a base64 version of all patterns. If I find a solution to convert them automatically and easily, I will let you know.

**Comment by DanielRuf** [comment]
I have uploaded here the converted images: 
http://daniel-ruf.de/subtlepatterns/index.html

You can get the base64 codes from the css file 
(I had to optimize some parts of the files in notepad++ after the automatic generation ):
http://daniel-ruf.de/subtlepatterns/subtlepatterns.css (it is about 13MB)

To generate the files, I used the script from 
http://code.google.com/p/image2css/ or 
https://github.com/mhuckaby/image2cssConverter

The used command line code was this (windows):
`>image2css.bat -f patterns/ -i png jpg -o subtlepatterns.css -h index.html`

**Comment by atlemo** [comment]
Ah, that's great - thanks!

**Comment by DanielRuf** [comment]
@subtlepatterns would be great if you could generate these files also and host them on subtlepatterns.com (and maybe here on github too) because I think it makes more sense when you host this.

Let me know when you have done this because I have to clean up a bit my server.
The combined css file is currently 13 megabytes big.

**Comment by atlemo** [comment]
You mean host the base64 files on subtlepatterns.com?
I'm sorry but I have no plans on doing this at the moment. The demand is just not there to support the extra work and bandwidth required. 
There will soon be retina size patterns too, and this will require even more of my time.
Hope you understand – those who want base64 versions can easily convert using the available online tools.

I might offer this service at a later point, but not right now.
