### ISSUE TITLE
.pat file corrupted?

### ISSUE THREAD

**Issue by himedlooff** [atlemo/SubtlePatterns#11]
Getting a file corrupted error when trying to use the .pat file in photoshop.

**Comment by atlemo** [comment]
I can't seem to get that error here. 
Try getting the latest file later this week when I update.

**Comment by himedlooff** [comment]
So sorry but I tried simply saving the .pat.zip file by right clicking it on github and choosing "save link as". I tried downloading the complete source this time and it's working great!
