### ISSUE TITLE
unzipped .pat File?

### ISSUE THREAD

**Issue by riconeitzel** [atlemo/SubtlePatterns#16]
I'm using github for subtle patterns. unfort. i always have to unzip the .pat file. is it a big deal to put it unzipped into git so i can directly use it in PS?

Best,
 Rico

**Comment by atlemo** [comment]
At the moment it's just a file size thing, it's larger and takes more time to upload. 
But I'm working on a plugin for Photoshop, so for now it will stay like it is.
