### ISSUE TITLE
Higher pixel density versions

### ISSUE THREAD

**Issue by funwithtriangles** [atlemo/SubtlePatterns#2]
Seeing as devices with "retina" screens are becoming more and more popular, with an increasing difference between virtual CSS pixels and actual pixels, would it be wise to start asking contributors to make at least two versions of their images? 

Otherwise these beautiful patterns will start looking a bit crappy on those super sharp screens!

**Comment by atlemo** [comment]
Yes, this is something I'm looking in to. There has been quite a few requests. 
For now though, you can still use them for high DPI projects as they all tile, but some will work better than others at the smaller visual size.
But I'm quite sure I'll implement some sort of "2X" rez function in the (hopefully near) future.

**Comment by funwithtriangles** [comment]
Good to know this has been thought about! One thing I've tried doing, which seems to work for the more "pixelly" based patterns, is scale them to 200% in Photoshop, using the "nearest neighbour" setting. This means that the extra pixels will still appear crisp, instead of having that fuzzy appearance when scaled with other methods. Something to consider doing to the back catalogue.

**Comment by atlemo** [comment]
The site is now updated with retina patterns. For now I'm not pushing them on Git, but I might end up pushing all the Zip files that has both versions.

**Comment by ryanolson** [comment]
+1 for @2x versions on github!

**Comment by oisinlavery** [comment]
+1 

A separate 2X .pat file would be great too.
