### ISSUE TITLE
Website is no longer available?

### ISSUE THREAD

**Issue by aliemre** [atlemo/SubtlePatterns#23]
Hi,

Currently, subtlepatterns.com is not reachable. Is it temporary? If it is, I would like to host it on my own server with new interface. Could you give me information about that?

**Comment by atlemo** [comment]
Hi. Not sure what you mean. The site is still up and running. 

Atle

**Comment by atlemo** [comment]
Is there anything I can do, other than “white listing” Turkey on my CDN?  

## 

Atle Mo

**Comment by aliemre** [comment]
Nothing. But it's weird not to reach the site. I forked the repository. So, I will use the patterns from here. Thanks.
