### ISSUE TITLE
subtlepatterns.com is out of date!

### ISSUE THREAD

**Issue by lijiapeng** [atlemo/SubtlePatterns#4]
site's down, what a pity!

**Comment by atlemo** [comment]
Domain has been hijacked.  
I'm working on it.

## 

Atle Mo
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by coltoncat** [comment]
Sympathies... who is your registrar...

On Tue, Sep 18, 2012 at 2:11 AM, Atle Mo notifications@github.com wrote:

> Domain has been hijacked.
> I'm working on it.
> 
> ## 
> 
> Atle Mo
> Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
> 
> On Tuesday, September 18, 2012 at 3:37 AM, Li Jiapeng wrote:
> 
> > site's down, what a pity!
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/subtlepatterns/SubtlePatterns/issues/4).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/subtlepatterns/SubtlePatterns/issues/4#issuecomment-8642555.

## 

Monday is an awful way to spend 1/7th of your life...

**Comment by atlemo** [comment]
It's restored to me now. 

Atle

Den 19. sep. 2012 kl. 03:12 skrev Max notifications@github.com:

> Sympathies... who is your registrar... 
>

**Comment by victorb** [comment]
Yep, restored here also. Think you can close issue.
