### ISSUE TITLE
Create a gh-pages version to allow hotlinking the patterns

### ISSUE THREAD

**Issue by chrisramakers** [atlemo/SubtlePatterns#9]
I don't know what this implies license wise but it would be really helpfull if you could set up a gh-pages branch for the SubtlePatterns repo so we can hotlink all patterns from there and use Github as a CDN for the patterns.

Hotlinking the raw files isn't the best idea latency wise, that's what gh-pages are for.

check http://code.lancepollard.com/github-as-a-cdn/ for more info

**Comment by hanoii** [comment]
Plus one for this, it should be very easy to do and very helpful

**Comment by hanoii** [comment]
I have just created a gh-pages branch
